<div class="problem-statement">
<div class="header">
<h1 class="title">C. Retry</h1>
<table>
<tr class="time-limit">
<td class="property-title">Ограничение времени</td>
<td>1 секунда</td>
</tr>
<tr class="memory-limit">
<td class="property-title">Ограничение памяти</td>
<td>64Mb</td>
</tr>
<tr class="input-file">
<td class="property-title">Ввод</td>
<td colspan="1">стандартный ввод или input.txt</td>
</tr>
<tr class="output-file">
<td class="property-title">Вывод</td>
<td colspan="1">стандартный вывод или output.txt</td>
</tr>
</table>
</div>
<h2></h2>
<div class="legend"><span style="">
<p>Иногда некоторые действия не получается выполнить с первого раза. Например, обращение по сети в сторонний сервис может обернуться
            неудачей из-за сетевых проблем или перегрузки сервиса. В таких случаях иногда пишут код, пытающийся повторить такое действие
            несколько раз подряд. 
         </p></span><p>Вам надо написать реализацию функции DoWithRetry с таким заголовком: <a href="https://clck.ru/EYTd3">https://clck.ru/EYTd3</a>. Функция принимает на вход другую функцию без аргументов, возвращающую значение типа Result, количество повторов, таймаут
         между повторами и флажок throwLast. Одним из шаблонных параметров функции является тип исключения, на которое функция реагирует.
         Функция должна вызвать func, и если произошло исключение указанного типа, то вызвать нашу функцию Sleep с параметром sleepTime,
         а затем повторить попытку (если попытки еще остались). Максимальное количество вызовов func, которое может получиться, равно
         retryCount + 1. Если на последней попытке происходит исключение указанного типа, и throwLast истинно, этот же объект исключения
         должен проброситься дальше из функции. Если же throwLast ложно, то надо просто вернуть <span style=""></span> (пустой объект std::optional). 
      </p>
<p>Если же вызов func закончился успешно, то надо просто вернуть результат func.</p>
</div>
<h2>Примечания</h2>
<div class="notes"><span style="">
<p>Про std::optional можно прочитать здесь: <a href="https://en.cppreference.com/w/cpp/utility/optional">https://en.cppreference.com/w/cpp/utility/optional</a>. Если исключение произошло на последней попытке, то после нее "спать" не надо.
         </p></span></div>
</div>